<?php $u = Auth::user(); $brandName = $brandName ?? Database::setting('school_name','SchoolCMS'); $brandLogo = Database::setting('logo',''); $uAvatar=$u['avatar']??''; $uName=trim($u['name']??'Admin'); $uInitial=mb_strtoupper(mb_substr($uName,0,1)); ?>
<div id="adminTopbar" class="bg-emerald-700 text-white shadow fixed top-0 inset-x-0 z-50" style="background:#047857!important;color:#fff!important;position:fixed;top:0;left:0;right:0;z-index:50"><div class="flex items-center justify-between px-4 py-2.5">
<div class="flex items-center gap-2"><button id="sideBtn" class="md:hidden w-9 h-9 border border-white/30 rounded-lg"><i class="fa fa-bars"></i></button><?php if($brandLogo): ?><img src="<?= Helper::upload($brandLogo) ?>" alt="" class="h-9 w-auto object-contain shrink-0" style="filter:drop-shadow(0 0 1px #fff) drop-shadow(0 0 6px rgba(255,255,255,.9)) drop-shadow(0 2px 8px rgba(255,255,255,.45))"><?php else: ?><span class="w-8 h-8 rounded-lg bg-white text-emerald-700 grid place-items-center font-extrabold"><?= Helper::e(mb_substr($brandName,0,1)) ?></span><?php endif; ?><span class="font-bold"><?= Helper::e($brandName) ?></span></div>
<div class="flex items-center gap-2 text-sm"><span class="hidden md:inline-flex items-center gap-1.5 px-2.5 py-1 bg-white/15 border border-white/20 rounded-lg font-mono text-xs"><i class="fa fa-calendar-day"></i><span data-clock-admin><?= Helper::tgl(date('Y-m-d')) ?> • <?= date('H:i') ?></span></span>
<?php try{ $mailDb=$db??Database::conn(); $mailDb->exec("CREATE TABLE IF NOT EXISTS contact_messages(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,email VARCHAR(190) NOT NULL,subject VARCHAR(190) NOT NULL DEFAULT '',message MEDIUMTEXT NOT NULL,is_read TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_read_created (is_read,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); $mailCount=(int)$mailDb->query("SELECT COUNT(*) FROM contact_messages WHERE is_read=0 AND created_at >= NOW() - INTERVAL 24 HOUR")->fetchColumn(); $mailRows=$mailDb->query("SELECT id,name,email,subject,is_read,created_at FROM contact_messages WHERE created_at >= NOW() - INTERVAL 24 HOUR ORDER BY is_read ASC, id DESC LIMIT 6")->fetchAll(); }catch(Throwable){ $mailCount=0; $mailRows=[]; } ?>
<div class="relative" id="mailDropWrap"><button id="mailBtn" type="button" class="relative w-9 h-9 grid place-items-center bg-white/15 border border-white/20 rounded-full hover:bg-white/25" title="Pesan masuk"><i class="fa fa-envelope"></i><?php if($mailCount>0): ?><span class="absolute -top-1 -right-1 min-w-[18px] h-[18px] px-1 rounded-full bg-amber-400 text-emerald-950 text-[10px] font-extrabold grid place-items-center"><?= $mailCount>9?'9+':$mailCount ?></span><?php endif; ?></button>
<div id="mailDrop" class="hidden absolute right-0 top-full mt-2 w-80 max-w-[85vw] bg-white text-slate-800 rounded-2xl shadow-2xl border overflow-hidden z-50"><div class="flex items-center gap-2 px-4 py-3 bg-slate-50 border-b"><b class="text-sm">Pesan Masuk</b><span class="text-[11px] px-2 py-0.5 rounded-full <?= $mailCount>0?'bg-emerald-600 text-white':'bg-slate-200 text-slate-600' ?> font-bold"><?= $mailCount ?> baru</span><form method="post" action="<?= Helper::url('admin/inbox') ?>" class="ml-auto"><?= Security::csrfField() ?><input type="hidden" name="act" value="read_all"><button class="text-[11px] font-bold text-emerald-700 hover:underline" title="Tandai semua dibaca">Semua dibaca</button></form></div><div class="max-h-80 overflow-y-auto divide-y"><?php if(!$mailRows): ?><p class="p-5 text-sm text-slate-500 text-center">Tidak ada pesan 24 jam terakhir.</p><?php endif; ?><?php foreach($mailRows as $m): $seen=(int)($m['is_read']??0)===1; ?><a href="<?= Helper::url('admin/inbox') ?>?hl=<?= (int)$m['id'] ?>" class="block px-4 py-3 hover:bg-slate-50"><span class="block text-sm truncate <?= $seen?'font-normal text-slate-600':'font-extrabold text-slate-900' ?>"><?= Helper::e($m['subject']!==''?$m['subject']:'(Tanpa subjek)') ?></span><span class="block text-xs truncate <?= $seen?'text-slate-400':'text-slate-600 font-semibold' ?>"><?= Helper::e($m['name']) ?> • <?= Helper::e($m['email']) ?></span><span class="block text-[11px] text-slate-400 mt-0.5"><?= Helper::e(Helper::tgl($m['created_at']).' '.substr((string)$m['created_at'],11,5)) ?></span></a><?php endforeach; ?></div><a href="<?= Helper::url('admin/inbox') ?>" class="block text-center text-xs font-bold text-emerald-700 hover:bg-emerald-50 px-4 py-2.5 border-t">Buka Kotak Masuk</a></div></div>
<div class="relative" id="userDropWrap"><button id="userBtn" type="button" class="flex items-center gap-2 pl-1 pr-2 py-1 bg-white/15 border border-white/20 rounded-full hover:bg-white/25"><?php if($uAvatar): ?><img src="<?= Helper::upload($uAvatar) ?>" alt="" class="w-7 h-7 rounded-full object-cover border border-white/40"><?php else: ?><span class="w-7 h-7 rounded-full bg-white text-emerald-700 grid place-items-center font-extrabold text-sm"><?= Helper::e($uInitial) ?></span><?php endif; ?><span class="font-bold max-w-[140px] truncate"><?= Helper::e($uName) ?></span><i class="fa fa-chevron-down text-[10px] opacity-70"></i></button>
<div id="userDrop" class="hidden absolute right-0 top-full mt-2 w-56 bg-white text-slate-800 rounded-2xl shadow-2xl border overflow-hidden z-50"><div class="p-4 flex items-center gap-3 bg-slate-50 border-b"><?php if($uAvatar): ?><img src="<?= Helper::upload($uAvatar) ?>" alt="" class="w-11 h-11 rounded-full object-cover border"><?php else: ?><span class="w-11 h-11 rounded-full bg-emerald-600 text-white grid place-items-center font-extrabold text-lg"><?= Helper::e($uInitial) ?></span><?php endif; ?><span class="min-w-0"><b class="block truncate"><?= Helper::e($uName) ?></b><span class="block text-xs text-slate-500 truncate"><?= Helper::e($u['username']??'') ?><?= !empty($u['role'])?' • '.Helper::e($u['role']):'' ?></span></span></div><div class="p-2 grid gap-1.5"><?php if(($u['role']??'')==='administrator'): ?><button id="sysUpdBtn" type="button" class="w-full flex items-center justify-center gap-2 px-3 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-bold"><i class="fa fa-rotate"></i>Update Sistem</button><?php endif; ?><form method="post" action="<?= Helper::url('admin/logout') ?>" data-confirm-logout><?= Security::csrfField() ?><button class="w-full flex items-center justify-center gap-2 px-3 py-2 rounded-xl bg-red-600 hover:bg-red-500 text-white text-sm font-bold"><i class="fa fa-right-from-bracket"></i>Logout</button></form></div></div></div></div>
</div></div>
<style>#userDropWrap:hover #userDrop{display:block!important}#userDropWrap #userDrop{transition:opacity .15s ease}#mailDropWrap #mailDrop{transition:opacity .15s ease}</style>
<script>document.getElementById('sysUpdBtn')?.addEventListener('click',async()=>{
  const url='<?= Helper::url('admin/system-update') ?>',csrf='<?= Security::csrfToken() ?>';
  const post=async d=>{const f=new FormData();f.append('csrf',csrf);Object.entries(d).forEach(([k,v])=>f.append(k,v));const r=await fetch(url,{method:'POST',body:f});return r.json()};
  const st=await post({sub:'status'}).catch(()=>({ok:false}));
  if(!st.ok){Swal.fire('Gagal','Tidak bisa baca status sistem.','error');return}
  if(st.lock){Swal.fire('Berjalan','Update sedang berjalan. Tunggu selesai.','info');return}
  const c=await post({sub:'check'}).catch(()=>({ok:false,msg:'Koneksi gagal.'}));
  if(!c.ok){Swal.fire('Gagal',c.msg||'Cek update gagal.','error');return}
  if(c.uptodate){Swal.fire('Terbaru','Sistem sudah versi terbaru.','success');return}
  const ok=await Swal.fire({title:'Terapkan update?',html:'Ditemukan <b>'+(c.behind??'?')+' perubahan baru</b>.<br>Backup otomatis dibuat dulu.<br>Data & database hosting <b>tidak ditimpa</b>.<br><span class="text-xs text-slate-500">Versi: '+c.local.slice(0,7)+' → '+c.remote.slice(0,7)+'</span>',icon:'question',showCancelButton:true,confirmButtonText:'Ya, Update',cancelButtonText:'Batal',confirmButtonColor:'#059669'}).then(r=>r.isConfirmed);
  if(!ok)return;
  Swal.fire({title:'Memproses...',html:'Mengambil & menerapkan update.<br>Jangan tutup halaman.',allowOutsideClick:false,allowEscapeKey:false,didOpen:()=>Swal.showLoading()});
  const a=await post({sub:'apply'}).catch(()=>({ok:false,msg:'Koneksi gagal.'}));
  if(a.ok){Swal.fire('Berhasil',a.msg||'Update selesai.','success')}else{Swal.fire('Gagal',a.msg||'Update gagal.','error')}
});
document.getElementById('sideBtn')?.addEventListener('click',()=>{const s=document.getElementById('sidebar'); if(!s)return; s.classList.toggle('hidden'); s.classList.toggle('open')});(function(){const w=document.getElementById('userDropWrap'),b=document.getElementById('userBtn'),d=document.getElementById('userDrop');if(!w||!b||!d)return;let t=null;const show=()=>{clearTimeout(t);d.classList.remove('hidden')};const hide=()=>{clearTimeout(t);t=setTimeout(()=>d.classList.add('hidden'),180)};w.addEventListener('mouseenter',show);w.addEventListener('mouseleave',hide);b.addEventListener('click',e=>{e.stopPropagation();d.classList.toggle('hidden')});document.addEventListener('click',e=>{if(!w.contains(e.target))d.classList.add('hidden')});document.addEventListener('keydown',e=>{if(e.key==='Escape')d.classList.add('hidden')})})();
(function(){const w=document.getElementById('mailDropWrap'),b=document.getElementById('mailBtn'),d=document.getElementById('mailDrop');if(!w||!b||!d)return;let t=null;const show=()=>{clearTimeout(t);d.classList.remove('hidden')};const hide=()=>{clearTimeout(t);t=setTimeout(()=>d.classList.add('hidden'),220)};w.addEventListener('mouseenter',show);w.addEventListener('mouseleave',hide);b.addEventListener('click',e=>{e.stopPropagation();d.classList.toggle('hidden')});d.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a)return;d.classList.add('hidden')});document.addEventListener('click',e=>{if(!w.contains(e.target))d.classList.add('hidden')});document.addEventListener('keydown',e=>{if(e.key==='Escape')d.classList.add('hidden')})})();</script>
