-- Migrasi section fleksibel
ALTER TABLE homepage_sections
  ADD COLUMN IF NOT EXISTS `type` VARCHAR(60) NOT NULL DEFAULT 'custom' AFTER section_key,
  ADD COLUMN IF NOT EXISTS content MEDIUMTEXT DEFAULT NULL AFTER subtitle,
  ADD COLUMN IF NOT EXISTS image VARCHAR(255) DEFAULT NULL AFTER content,
  ADD COLUMN IF NOT EXISTS btn_text VARCHAR(150) DEFAULT NULL AFTER image,
  ADD COLUMN IF NOT EXISTS btn_url VARCHAR(500) DEFAULT NULL AFTER btn_text,
  ADD COLUMN IF NOT EXISTS btn2_text VARCHAR(150) DEFAULT NULL AFTER btn_url,
  ADD COLUMN IF NOT EXISTS btn2_url VARCHAR(500) DEFAULT NULL AFTER btn2_text,
  ADD COLUMN IF NOT EXISTS style VARCHAR(60) NOT NULL DEFAULT 'default' AFTER btn2_url,
  ADD COLUMN IF NOT EXISTS bg VARCHAR(30) DEFAULT '' AFTER style,
  ADD COLUMN IF NOT EXISTS padding VARCHAR(10) NOT NULL DEFAULT 'lg' AFTER bg,
  ADD COLUMN IF NOT EXISTS align VARCHAR(10) NOT NULL DEFAULT 'left' AFTER padding,
  ADD COLUMN IF NOT EXISTS items_limit INT NOT NULL DEFAULT 3 AFTER align;

UPDATE homepage_sections SET `type`=section_key WHERE `type`='custom' OR `type`='';
