<?php declare(strict_types=1); Auth::requireRole(['administrator','editor']); $title='Pengaturan Tampilan';
$keys=['hero_align','facebook','instagram','youtube','tiktok','service_days','service_open','service_close'];
if($_SERVER['REQUEST_METHOD']==='POST'){if(!Security::verifyCsrf($_POST['csrf']??null)){Session::flash('err','CSRF tidak valid.');header('Location: '.Helper::url('admin/appearance'));exit;}foreach($keys as $k){if(!array_key_exists($k,$_POST))continue;$v=trim((string)$_POST[$k]);$db->prepare("INSERT INTO settings(`key`,`value`) VALUES(?,?) ON DUPLICATE KEY UPDATE `value`=VALUES(`value`)")->execute([$k,$v]);}
if(!empty($_POST['favicon_clear'])){$old=$db->query("SELECT `value` FROM settings WHERE `key`='favicon'")->fetchColumn();if($old)@unlink(ROOT.'/assets/uploads/'.basename((string)$old));$db->prepare("DELETE FROM settings WHERE `key`='favicon'")->execute();}
elseif(!empty($_FILES['favicon']['name']??'')){ $f=$_FILES['favicon']; $ext=strtolower(pathinfo((string)$f['name'],PATHINFO_EXTENSION)); $err='';
if(in_array($ext,['ico'],true)){ if(($f['error']??4)!==0)$err='Upload favicon gagal.'; elseif(($f['size']??0)>512*1024)$err='Favicon maksimal 512KB.'; }
else { $err=Security::validImage($f,$APP)?:''; if($err===''&&!in_array($ext,['png','jpg','jpeg','webp','gif'],true))$err='Format favicon harus ICO/PNG/JPG/WebP.'; }
if($err!==''){Session::flash('err',$err);header('Location: '.Helper::url('admin/appearance'));exit;}
$old=$db->query("SELECT `value` FROM settings WHERE `key`='favicon'")->fetchColumn(); $n=Security::safeName($f['name']); move_uploaded_file($f['tmp_name'],ROOT.'/assets/uploads/'.$n); $db->prepare("INSERT INTO settings(`key`,`value`) VALUES('favicon',?) ON DUPLICATE KEY UPDATE `value`=VALUES(`value`)")->execute([$n]); if($old&&$old!==$n)@unlink(ROOT.'/assets/uploads/'.basename((string)$old)); }
Auth::log($db,'update','settings','Ubah pengaturan tampilan');Session::flash('ok','Pengaturan tampilan disimpan.');header('Location: '.Helper::url('admin/appearance'));exit;}
$sets=[];foreach($db->query("SELECT `key`,`value` FROM settings") as $r)$sets[$r['key']]=$r['value'];require ROOT.'/templates/admin/header.php';?>
<div class="flex flex-wrap items-center gap-3 mb-4"><div><h1 class="text-xl font-extrabold"><i class="fa fa-display text-emerald-600 mr-1"></i>Pengaturan Tampilan</h1><p class="text-sm text-slate-500">Atur komponen visual halaman publik tanpa menyentuh kode.</p></div><a href="<?=Helper::url()?>" target="_blank" class="ml-auto border rounded-xl px-4 py-2 text-sm bg-white"><i class="fa fa-eye mr-1"></i>Preview Situs</a></div>
<form method="post" enctype="multipart/form-data" data-loading class="grid lg:grid-cols-2 gap-4"><?=Security::csrfField()?>
<section class="bg-white rounded-2xl border p-5 grid gap-3"><div><h2 class="font-extrabold"><i class="fa fa-star text-emerald-600 mr-1"></i>Favicon</h2><p class="text-xs text-slate-500 mt-1">Ikon tab browser. Format ICO/PNG/JPG/WebP, maks 512KB. Kosong = ikut logo sekolah.</p></div><div class="flex items-center gap-3"><?php $favPrev=$sets['favicon']??''; $logoPrev=$sets['logo']??''; $favSrc=$favPrev?Helper::upload($favPrev):($logoPrev?Helper::upload($logoPrev):''); ?><?php if($favSrc!==''): ?><img id="favPreview" src="<?=Helper::e($favSrc)?>" alt="Favicon" class="h-12 w-12 object-contain rounded-xl border bg-slate-50 p-1.5"><?php else: ?><img id="favPreview" class="hidden h-12 w-12 object-contain rounded-xl border bg-slate-50 p-1.5" alt="Preview"><?php endif; ?><div class="text-xs text-slate-500"><?php if(!empty($favPrev)): ?><span class="font-bold text-emerald-700">Favicon kustom aktif.</span><?php elseif(!empty($logoPrev)): ?><span>Belum ada favicon — memakai <b>logo sekolah</b>.</span><?php else: ?><span>Belum ada favicon & logo — memakai ikon bawaan.</span><?php endif; ?></div></div><label class="grid gap-1 text-sm font-semibold">Upload favicon<input type="file" name="favicon" id="favInput" accept=".ico,.png,.jpg,.jpeg,.webp,.gif,image/*" class="border rounded-lg p-2 font-normal bg-white"></label><?php if(!empty($favPrev)): ?><label class="text-xs flex gap-1.5 items-center font-normal"><input type="checkbox" name="favicon_clear" value="1"> Hapus favicon (kembali ke logo sekolah)</label><?php endif; ?></section>

<section class="bg-white rounded-2xl border p-5 grid gap-3"><div><h2 class="font-extrabold"><i class="fa fa-align-center text-emerald-600 mr-1"></i>Hero Laman</h2><p class="text-xs text-slate-500 mt-1">Atur perataan teks hero semua laman publik.</p></div><label class="grid gap-1 text-sm font-semibold">Perataan hero<select name="hero_align" class="border rounded-lg p-2 font-normal"><option value="left" <?=($sets['hero_align']??'center')==='left'?'selected':''?>>Kiri</option><option value="center" <?=($sets['hero_align']??'center')==='center'?'selected':''?>>Tengah</option><option value="right" <?=($sets['hero_align']??'center')==='right'?'selected':''?>>Kanan</option></select></label></section>
<section class="bg-white rounded-2xl border p-5 grid gap-3"><div><h2 class="font-extrabold"><i class="fa fa-share-nodes text-emerald-600 mr-1"></i>Media Sosial</h2><p class="text-xs text-slate-500 mt-1">Tautan profil media sosial yang tampil di situs.</p></div><?php foreach(['facebook'=>'Facebook','instagram'=>'Instagram','youtube'=>'YouTube','tiktok'=>'TikTok'] as $k=>$l): ?><label class="grid gap-1 text-sm font-semibold"><?= $l ?><input name="<?= $k ?>" value="<?= Helper::e($sets[$k]??'') ?>" placeholder="https://..." class="border rounded-lg p-2 font-normal"></label><?php endforeach; ?></section>
<section class="bg-white rounded-2xl border p-5 grid gap-3"><div><h2 class="font-extrabold"><i class="fa fa-clock text-emerald-600 mr-1"></i>Jam Layanan Kontak</h2><p class="text-xs text-slate-500 mt-1">Jam operasional yang tampil di halaman kontak.</p></div><label class="grid gap-1 text-sm font-semibold">Hari<input name="service_days" value="<?= Helper::e($sets['service_days']??'Senin - Jumat') ?>" placeholder="Senin - Jumat" class="border rounded-lg p-2 font-normal"></label><div class="grid grid-cols-2 gap-2"><label class="grid gap-1 text-sm font-semibold">Jam Buka<input type="time" name="service_open" value="<?= Helper::e($sets['service_open']??'07:00') ?>" class="border rounded-lg p-2 font-normal"></label><label class="grid gap-1 text-sm font-semibold">Jam Tutup<input type="time" name="service_close" value="<?= Helper::e($sets['service_close']??'15:30') ?>" class="border rounded-lg p-2 font-normal"></label></div></section>
<div class="lg:col-span-2 flex justify-center"><button class="bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl px-8 py-2 font-bold w-full sm:w-auto sm:min-w-[200px]"><i class="fa fa-floppy-disk mr-1"></i>Simpan</button></div>
</form>
<script>
document.getElementById('favInput')?.addEventListener('change',e=>{
  const f=e.target.files?.[0],img=document.getElementById('favPreview');
  if(!f||!img)return;
  img.src=URL.createObjectURL(f);img.classList.remove('hidden');
});
</script>
<?php require ROOT.'/templates/admin/footer.php';?>




