<?php declare(strict_types=1); Auth::requireRole(['administrator','editor']); $title='Pengaturan Tampilan';
$keys=['news_empty_text','share_heading','share_description','news_carousel_mobile_height','news_carousel_desktop_height','news_carousel_speed','news_carousel_limit','news_carousel_style'];
if($_SERVER['REQUEST_METHOD']==='POST'){if(!Security::verifyCsrf($_POST['csrf']??null)){Session::flash('err','CSRF tidak valid.');header('Location: '.Helper::url('admin/appearance'));exit;}foreach($keys as $k){if(!array_key_exists($k,$_POST))continue;$v=trim((string)$_POST[$k]);$db->prepare("INSERT INTO settings(`key`,`value`) VALUES(?,?) ON DUPLICATE KEY UPDATE `value`=VALUES(`value`)")->execute([$k,$v]);}Auth::log($db,'update','settings','Ubah pengaturan tampilan');Session::flash('ok','Pengaturan tampilan disimpan.');header('Location: '.Helper::url('admin/appearance'));exit;}
$sets=[];foreach($db->query("SELECT `key`,`value` FROM settings") as $r)$sets[$r['key']]=$r['value'];require ROOT.'/templates/admin/header.php';?>
<div class="flex flex-wrap items-center gap-3 mb-4"><div><h1 class="text-xl font-extrabold"><i class="fa fa-display text-emerald-600 mr-1"></i>Pengaturan Tampilan</h1><p class="text-sm text-slate-500">Atur komponen visual halaman publik tanpa menyentuh kode.</p></div><a href="<?=Helper::url()?>" target="_blank" class="ml-auto border rounded-xl px-4 py-2 text-sm bg-white"><i class="fa fa-eye mr-1"></i>Preview Situs</a></div>
<form method="post" data-loading class="grid lg:grid-cols-2 gap-4"><?=Security::csrfField()?>
<section class="bg-white rounded-2xl border p-5 grid gap-3"><div><h2 class="font-extrabold"><i class="fa fa-newspaper text-emerald-600 mr-1"></i>Halaman Berita</h2><p class="text-xs text-slate-500 mt-1">Teks pendukung halaman daftar dan detail berita.</p></div><label class="grid gap-1 text-sm font-semibold">Pesan saat berita kosong<input name="news_empty_text" value="<?=Helper::e($sets['news_empty_text']??'Belum ada berita pada kategori ini.')?>" class="border rounded-lg p-2 font-normal"></label><label class="grid gap-1 text-sm font-semibold">Judul panel berbagi<input name="share_heading" value="<?=Helper::e($sets['share_heading']??'Bagikan berita ini')?>" class="border rounded-lg p-2 font-normal"></label><label class="grid gap-1 text-sm font-semibold">Deskripsi panel berbagi<textarea name="share_description" rows="3" class="border rounded-lg p-2 font-normal"><?=Helper::e($sets['share_description']??'Sebarkan informasi kepada keluarga dan teman.')?></textarea></label></section>
<section class="bg-white rounded-2xl border p-5 grid gap-3"><div><h2 class="font-extrabold"><i class="fa fa-images text-emerald-600 mr-1"></i>Carousel Berita</h2><p class="text-xs text-slate-500 mt-1">Sesuaikan ukuran, ritme, jumlah feed, dan bentuk carousel.</p></div><div class="grid sm:grid-cols-2 gap-3"><?php foreach(['news_carousel_mobile_height'=>['Tinggi mobile','200',150,420],'news_carousel_desktop_height'=>['Tinggi desktop','270',180,520],'news_carousel_speed'=>['Kecepatan autoplay','5000',1000,20000],'news_carousel_limit'=>['Jumlah feed','5',1,10]] as $k=>$c):?><label class="grid gap-1 text-sm font-semibold"><?=$c[0]?><input type="number" min="<?=$c[2]?>" max="<?=$c[3]?>" name="<?=$k?>" value="<?=Helper::e($sets[$k]??$c[1])?>" class="border rounded-lg p-2 font-normal"></label><?php endforeach;?></div><label class="grid gap-1 text-sm font-semibold">Gaya carousel<select name="news_carousel_style" class="border rounded-lg p-2 font-normal"><option value="rounded" <?=($sets['news_carousel_style']??'rounded')==='rounded'?'selected':''?>>Rounded Card</option><option value="wide" <?=($sets['news_carousel_style']??'')==='wide'?'selected':''?>>Wide Editorial</option><option value="compact" <?=($sets['news_carousel_style']??'')==='compact'?'selected':''?>>Compact Modern</option></select></label></section>
<div class="lg:col-span-2 flex justify-center"><button class="bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl px-8 py-2 font-bold w-full sm:w-auto sm:min-w-[200px]"><i class="fa fa-floppy-disk mr-1"></i>Simpan</button></div>
<?php require ROOT.'/templates/admin/footer.php';?>

