<?php declare(strict_types=1); Auth::requireRole(['administrator','editor']); $title='Tema & Warna';
$presets=['emerald'=>['Emerald Academy','#059669','#f59e0b','Hijau pendidikan yang segar'], 'ocean'=>['Ocean Scholar','#0284c7','#f59e0b','Biru akademik yang tenang'], 'royal'=>['Royal School','#4f46e5','#fbbf24','Elegan dan berwibawa'], 'burgundy'=>['Burgundy Classic','#9f1239','#d4a72c','Klasik dan berkelas'], 'forest'=>['Forest Campus','#166534','#facc15','Natural dan berkarakter'], 'coral'=>['Coral Creative','#e11d48','#06b6d4','Modern dan penuh energi'], 'midnight'=>['Midnight Elite','#334155','#38bdf8','Minimalis premium'], 'sunrise'=>['Sunrise Learning','#ea580c','#0891b2','Hangat dan optimistis']];
if($_SERVER['REQUEST_METHOD']==='POST'){if(!Security::verifyCsrf($_POST['csrf']??null)){Session::flash('err','CSRF tidak valid.');header('Location: '.Helper::url('admin/themes'));exit;}$theme=$_POST['theme']??'elegant';$palette=$_POST['palette']??'emerald';if(!in_array($theme,['elegant','classic','vibrant','editorial','minimal'],true))$theme='elegant';if(!isset($presets[$palette]))$palette='emerald';$vals=['site_theme'=>$theme,'theme_palette'=>$palette,'theme_primary'=>$_POST['theme_primary']??$presets[$palette][1],'theme_accent'=>$_POST['theme_accent']??$presets[$palette][2],'theme_radius'=>in_array($_POST['theme_radius']??'', ['soft','square','round'],true)?$_POST['theme_radius']:'soft'];foreach($vals as $k=>$v){if(in_array($k,['theme_primary','theme_accent'],true)&&!preg_match('/^#[0-9a-fA-F]{6}$/',(string)$v))continue;$db->prepare("INSERT INTO settings(`key`,`value`) VALUES(?,?) ON DUPLICATE KEY UPDATE `value`=VALUES(`value`)")->execute([$k,$v]);}Auth::log($db,'update','settings','Ubah tema dan warna');Session::flash('ok','Tema dan warna disimpan.');header('Location: '.Helper::url('admin/themes'));exit;}
$sets=[];foreach($db->query('SELECT `key`,`value` FROM settings') as $r)$sets[$r['key']]=$r['value'];$theme=$sets['site_theme']??'elegant';$palette=$sets['theme_palette']??'emerald';$primary=$sets['theme_primary']??$presets[$palette][1];$accent=$sets['theme_accent']??$presets[$palette][2];require ROOT.'/templates/admin/header.php';?>
<h1 class="text-xl font-extrabold mb-1"><i class="fa fa-palette text-emerald-600 mr-1"></i>Tema & Warna Website</h1><p class="text-sm text-slate-500 mb-4">Padukan template dengan palet warna apa pun sesuai identitas sekolah.</p>
<form method="post" class="grid gap-4" data-loading><?=Security::csrfField()?>
<div class="bg-white rounded-2xl border p-4"><h2 class="font-bold mb-3">Template Tampilan</h2><div class="grid sm:grid-cols-2 lg:grid-cols-5 gap-3">
<?php foreach(['elegant'=>['Modern Elegant','Bersih & profesional','from-slate-900 to-emerald-700'],'classic'=>['Academic Classic','Formal & berwibawa','from-blue-950 to-amber-500'],'vibrant'=>['Creative Campus','Cerah & dinamis','from-sky-500 via-emerald-500 to-orange-400'],'editorial'=>['School Editorial','Majalah sekolah modern','from-rose-700 to-orange-400'],'minimal'=>['Minimal Focus','Ringkas & tenang','from-slate-500 to-slate-900']] as $k=>$v): ?><label class="border-2 rounded-2xl p-3 cursor-pointer hover:border-emerald-400 has-[:checked]:border-emerald-600 has-[:checked]:bg-emerald-50"><input type="radio" name="theme" value="<?=$k?>" class="float-right" <?=$theme===$k?'checked':''?>><span class="block h-14 rounded-xl bg-gradient-to-br <?=$v[2]?> mb-2"></span><b><?=$v[0]?></b><span class="block text-xs text-slate-500"><?=$v[1]?></span></label><?php endforeach; ?></div></div>
<div class="bg-white rounded-2xl border p-4"><h2 class="font-bold mb-3">Palet Warna</h2><div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><?php foreach($presets as $k=>$v): ?><label class="flex items-center gap-3 border rounded-xl p-3 cursor-pointer hover:border-emerald-400 has-[:checked]:border-emerald-600"><input type="radio" name="palette" value="<?=$k?>" data-primary="<?=$v[1]?>" data-accent="<?=$v[2]?>" <?=$palette===$k?'checked':''?>><span class="w-12 h-10 rounded-lg" style="background:linear-gradient(135deg,<?=$v[1]?>,<?=$v[2]?>)"></span><span><b class="block text-sm"><?=$v[0]?></b><small class="text-slate-500"><?=$v[3]?></small></span></label><?php endforeach; ?></div></div>
<div class="bg-white rounded-2xl border p-4 grid sm:grid-cols-3 gap-3"><label class="grid gap-1 font-semibold">Warna utama<input id="themePrimary" type="color" name="theme_primary" value="<?=Helper::e($primary)?>" class="h-11 w-full border rounded-lg p-1"></label><label class="grid gap-1 font-semibold">Warna aksen<input id="themeAccent" type="color" name="theme_accent" value="<?=Helper::e($accent)?>" class="h-11 w-full border rounded-lg p-1"></label><label class="grid gap-1 font-semibold">Radius kartu<select name="theme_radius" class="border rounded-lg p-2"><?php foreach(['soft'=>'Lembut','square'=>'Tegas','round'=>'Membulat'] as $k=>$v): ?><option value="<?=$k?>" <?=($sets['theme_radius']??'soft')===$k?'selected':''?>><?=$v?></option><?php endforeach; ?></select></label></div><button class="bg-emerald-600 text-white rounded-xl py-2.5 font-bold">Simpan Tema</button></form>
<script>document.querySelectorAll('input[name="palette"]').forEach(p=>p.addEventListener('change',()=>{document.getElementById('themePrimary').value=p.dataset.primary;document.getElementById('themeAccent').value=p.dataset.accent}))</script><?php require ROOT.'/templates/admin/footer.php';?>
