</main>
<?php $ft = Database::setting('footer_text',Database::setting('school_name',''));
try { $fm = Database::conn()->query("SELECT * FROM menus WHERE location='footer' LIMIT 1")->fetch(); $fitems = [];
if ($fm) { $fs = Database::conn()->prepare("SELECT * FROM menu_items WHERE menu_id=? AND is_active=1 ORDER BY sort_order"); $fs->execute([$fm['id']]); $fitems = $fs->fetchAll(); } } catch (Throwable) { $fitems = []; }
if (!$fitems) $fitems = [['label'=>'Profil','url'=>'/profil'],['label'=>'Berita','url'=>'/berita'],['label'=>'Galeri','url'=>'/galeri'],['label'=>'Kontak','url'=>'/kontak']]; ?>
<?php try{$footerWidgets=Database::conn()->query("SELECT * FROM widgets WHERE area='footer' AND is_active=1 ORDER BY sort_order,id")->fetchAll();}catch(Throwable){$footerWidgets=[];} ?>
<footer class="relative overflow-hidden bg-slate-950 text-slate-300 mt-auto w-full">
<div class="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-emerald-600 via-amber-500 to-emerald-600"></div>
<div class="absolute -top-32 -right-24 w-80 h-80 rounded-full bg-emerald-600/10 blur-3xl pointer-events-none"></div>
<div class="max-w-7xl mx-auto px-4 py-12 grid md:grid-cols-4 gap-8 text-sm">
<div><span class="inline-flex w-11 h-11 rounded-xl bg-emerald-600 text-white items-center justify-center font-extrabold mb-3"><?= Helper::e(mb_substr(Database::setting('school_name','S'),0,1)) ?></span><h4 class="font-bold text-white mb-2">Tentang Sekolah</h4><p><?= Helper::e(Database::setting('school_name','SMK Nusantara')) ?> - <?= Helper::e(Database::setting('tagline','')) ?></p><p class="mt-2 text-slate-400"><?= Helper::e(Database::setting('address','')) ?></p></div>
<div><h4 class="font-bold text-white mb-3">Navigasi</h4><?php foreach($fitems as $fi): [$fhref,$ftgt]=Helper::menuUrl($fi['url']); ?><a href="<?= Helper::e($fhref) ?>"<?= $ftgt==='_blank'?' target="_blank" rel="noopener noreferrer"':'' ?> class="block py-1.5 hover:text-white hover:translate-x-1"><i class="fa fa-chevron-right text-[9px] text-emerald-500 mr-2"></i><?= Helper::e($fi['label']) ?></a><?php endforeach; ?></div>
<div><h4 class="font-bold text-white mb-2">Kontak</h4><p><?= Helper::e(Database::setting('phone','')) ?></p><p><?= Helper::e(Database::setting('email','')) ?></p></div>
<div><h4 class="font-bold text-white mb-3">Ikuti Kami</h4><div class="flex gap-2"><?php foreach(['facebook'=>'fa-facebook-f','instagram'=>'fa-instagram','youtube'=>'fa-youtube','tiktok'=>'fa-tiktok'] as $social=>$icon): $socialUrl=Database::setting($social,''); if(!$socialUrl)continue; ?><a href="<?= Helper::e($socialUrl) ?>" target="_blank" rel="noopener noreferrer" aria-label="<?= ucfirst($social) ?>" class="w-10 h-10 rounded-xl bg-white/10 grid place-items-center hover:bg-emerald-600 hover:text-white hover:-translate-y-1"><i class="fab <?= $icon ?>"></i></a><?php endforeach; ?></div></div>
<?php foreach($footerWidgets as $fw):$fwc=trim((string)($fw['content']??'')); ?><div><h4 class="font-bold text-white mb-3"><?= Helper::e($fw['title']?:'Informasi') ?></h4><?php if($fw['type']==='image'&&$fwc!==''): $fwi=(preg_match('~^(?:https?:)?//~i',$fwc)||str_starts_with($fwc,'/'))?$fwc:Helper::upload($fwc); ?><img src="<?= Helper::e($fwi) ?>" alt="<?= Helper::e($fw['title']?:'Footer') ?>" class="max-w-full max-h-36 rounded-xl object-contain"><?php elseif($fw['type']==='html'): ?><div class="text-sm text-slate-300 leading-relaxed"><?= $fwc ?></div><?php elseif($fw['type']==='contact'): ?><div class="grid gap-1.5 text-sm"><p><i class="fa fa-location-dot text-emerald-500 w-5"></i><?= Helper::e(Database::setting('address','-')) ?></p><p><i class="fa fa-phone text-emerald-500 w-5"></i><?= Helper::e(Database::setting('phone','-')) ?></p><p><i class="fa fa-envelope text-emerald-500 w-5"></i><?= Helper::e(Database::setting('email','-')) ?></p></div><?php elseif($fw['type']==='social'): ?><div class="flex flex-wrap gap-2"><?php foreach(['facebook'=>'fa-facebook-f','instagram'=>'fa-instagram','youtube'=>'fa-youtube','tiktok'=>'fa-tiktok'] as $fsn=>$fsi):$fsu=Database::setting($fsn,'');if(!$fsu)continue;?><a href="<?= Helper::e($fsu) ?>" target="_blank" rel="noopener noreferrer" class="w-9 h-9 rounded-xl bg-white/10 grid place-items-center hover:bg-emerald-600" aria-label="<?= ucfirst($fsn) ?>"><i class="fab <?= $fsi ?>"></i></a><?php endforeach; ?></div><?php else: ?><div class="text-sm text-slate-300 leading-relaxed"><?= nl2br(Helper::e($fwc)) ?></div><?php endif; ?></div><?php endforeach; ?>
</div>
<div class="border-t border-white/10"><div class="max-w-7xl mx-auto px-4 py-4 flex flex-col md:flex-row justify-between text-xs gap-2">
<span>&copy; <?= date('Y') ?> <?= Helper::e($ft) ?>.</span>
<a href="<?= Helper::url('admin/login') ?>" target="_blank" rel="noopener noreferrer" class="hover:text-white">Login Admin</a>
</div></div>
</footer>
<button id="toTop" aria-label="Kembali ke atas" class="fixed bottom-5 right-5 z-50 w-11 h-11 rounded-full bg-emerald-600 text-white shadow-lg grid place-items-center opacity-0 invisible translate-y-3 transition-all duration-300 hover:bg-emerald-500"><i class="fa fa-arrow-up"></i></button>
<script src="<?= Helper::asset('js/app.js') ?>"></script>
</body></html>
