<?php
try{$db->exec("ALTER TABLE categories ADD COLUMN grid_style VARCHAR(30) NOT NULL DEFAULT 'cards-3' AFTER description");}catch(Throwable){}
$cats=$db->query("SELECT c.*,COUNT(p.id) total FROM categories c LEFT JOIN posts p ON p.category_id=c.id AND p.status='published' AND p.deleted_at IS NULL GROUP BY c.id ORDER BY c.name")->fetchAll();
$catSlug=trim($_GET['kategori']??'');$active=null;foreach($cats as $c)if($c['slug']===$catSlug)$active=$c;
$baseWhere="p.status='published' AND p.deleted_at IS NULL";$metaTitle=($active?$active['name'].' - ':'').'Berita '.Database::setting('school_name','Sekolah');$newsEmpty=Database::setting('news_empty_text','Belum ada berita pada kategori ini.');require ROOT.'/templates/frontend/header.php';
function newsCard(array $p,string $extra=''):string{$cv=Helper::cover($p['featured_image']??'','berita-'.$p['slug'],800,520);return '<article class="group bg-white dark:bg-slate-800 rounded-2xl border overflow-hidden card-hover reveal '.$extra.'"><a href="'.Helper::url('berita/'.$p['slug']).'" class="block overflow-hidden"><img src="'.Helper::e($cv).'" alt="'.Helper::e($p['title']).'" class="w-full h-48 object-cover group-hover:scale-105 transition duration-700" loading="lazy"></a><div class="p-4"><a href="'.Helper::url('berita?kategori='.($p['cat_slug']??'')).'" class="text-[10px] uppercase tracking-wider font-bold text-emerald-600">'.Helper::e($p['cat']??'Berita').'</a><h3 class="font-extrabold text-lg leading-snug mt-1.5"><a href="'.Helper::url('berita/'.$p['slug']).'">'.Helper::e($p['title']).'</a></h3><p class="text-xs text-slate-400 mt-2">'.Helper::tgl($p['published_at']??$p['created_at']).' &bull; '.number_format((int)$p['views']).' dibaca</p><p class="text-sm text-slate-500 mt-2 line-clamp-2">'.Helper::e(Helper::excerpt($p['excerpt']?:$p['content'],100)).'</p></div></article>';}
function newsGrid(array $rows,string $style):string{ob_start();if($style==='masonry'){echo '<div class="columns-1 sm:columns-2 lg:columns-3 gap-5">';foreach($rows as $p)echo '<div class="break-inside-avoid mb-5">'.newsCard($p).'</div>';echo '</div>';}elseif($style==='timeline'){echo '<div class="max-w-7xl border-l-2 border-emerald-200 pl-7 space-y-5">';foreach($rows as $p)echo '<div class="relative">'.newsCard($p).'</div>';echo '</div>';}else{$cols=in_array($style,['cards-2','horizontal'],true)?'md:grid-cols-2':($style==='cards-4'?'sm:grid-cols-2 lg:grid-cols-4':'md:grid-cols-3');echo '<div class="grid '.$cols.' gap-5">';foreach($rows as $i=>$p)echo newsCard($p,$style==='magazine'&&$i===0?'md:col-span-2':($style==='horizontal'?'sm:grid sm:grid-cols-[180px_1fr]':''));echo '</div>';}return ob_get_clean();}
$fetch=function(string $where,array $args=[],int $limit=6)use($db,$baseWhere){$st=$db->prepare("SELECT p.*,c.name cat,c.slug cat_slug FROM posts p LEFT JOIN categories c ON c.id=p.category_id WHERE $baseWhere".($where?' AND '.$where:'')." ORDER BY p.published_at DESC LIMIT $limit");$st->execute($args);return $st->fetchAll();};
$carouselLimit=max(1,min(10,(int)Database::setting('news_carousel_limit','5')));$carouselSpeed=max(1000,min(20000,(int)Database::setting('news_carousel_speed','5000')));$carouselMobile=max(150,min(420,(int)Database::setting('news_carousel_mobile_height','200')));$carouselDesktop=max(180,min(520,(int)Database::setting('news_carousel_desktop_height','270')));$featured=$fetch('',[],$carouselLimit);
if($active){$posts=$fetch('p.category_id=?',[$active['id']],12);$grid=$active['grid_style']??'cards-3';}
?>
<div class="max-w-7xl mx-auto px-4 pt-2 pb-6 md:pt-3 md:pb-10">
<?php if($active): ?>
<?php if(!$posts):?><div class="rounded-3xl border bg-white p-14 text-center text-slate-500"><?=Helper::e($newsEmpty)?></div><?php else:echo newsGrid($posts,$grid);endif;?>
<?php else: ?>
<?php if($featured):?><section class="mb-14"><div class="flex items-end justify-between mb-5"><div><span class="text-xs font-bold uppercase tracking-[.2em] text-emerald-600">Sorotan terbaru</span><h2 class="text-2xl md:text-3xl font-extrabold mt-1">Kabar utama sekolah</h2></div></div><div class="relative overflow-hidden rounded-3xl bg-slate-950 text-white grid" data-carousel><?php foreach($featured as $i=>$p):$cv=Helper::cover($p['featured_image']??'','featured-'.$p['slug'],1200,700);?><article data-slide class="col-start-1 row-start-1 <?= $i?'opacity-0 pointer-events-none':'opacity-100' ?> transition-opacity duration-700"><img src="<?=Helper::e($cv)?>" alt="<?=Helper::e($p['title'])?>" class="absolute inset-0 w-full h-full object-cover"><span class="absolute inset-0 bg-gradient-to-r from-slate-950/90 via-slate-900/45 to-transparent"></span><div class="relative flex items-center w-full p-6 md:p-12 text-left"><div class="max-w-2xl w-full text-left ml-0 mr-auto flex flex-col justify-center items-start my-auto"><span class="text-xs font-bold uppercase tracking-wider text-emerald-300"><?=Helper::e($p['cat']??'Berita')?></span><h3 class="text-2xl md:text-4xl font-extrabold mt-2 leading-tight text-left"><?=Helper::e($p['title'])?></h3><p class="text-sm text-slate-300 mt-3 max-w-xl text-left"><?=Helper::e(Helper::excerpt($p['excerpt']?:$p['content'],150))?></p><a href="<?=Helper::url('berita/'.$p['slug'])?>" class="inline-flex mt-5 bg-emerald-600 text-white px-5 py-2.5 rounded-xl font-bold">Baca berita <i class="fa fa-arrow-right ml-2 mt-1 text-xs"></i></a></div></div></article><?php endforeach;?><button data-prev aria-label="Sebelumnya" class="absolute left-3 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-white/20 grid place-items-center"><i class="fa fa-chevron-left"></i></button><button data-next aria-label="Berikutnya" class="absolute right-3 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-white/20 grid place-items-center"><i class="fa fa-chevron-right"></i></button></div></section><?php endif;?>
<?php foreach($cats as $c):$rows=$fetch('p.category_id=?',[$c['id']],4);if(!$rows)continue;$g=$c['grid_style']??'cards-3';$cols=$g==='cards-2'?'md:grid-cols-2':($g==='cards-4'?'sm:grid-cols-2 lg:grid-cols-4':'md:grid-cols-3');?><section class="mb-14"><div class="flex flex-wrap items-end justify-between gap-3 mb-5"><div><span class="text-xs font-bold uppercase tracking-[.18em] text-emerald-600">Kategori berita</span><h2 class="text-2xl font-extrabold mt-1"><?=Helper::e($c['name'])?></h2><?php if($c['description']):?><p class="text-sm text-slate-500 mt-1"><?=Helper::e($c['description'])?></p><?php endif;?></div><a href="<?=Helper::url('berita?kategori='.$c['slug'])?>" class="text-sm font-bold text-emerald-600">Lihat semua <i class="fa fa-arrow-right ml-1"></i></a></div><div class="grid <?=$cols?> gap-5"><?php foreach($rows as $p)echo newsCard($p);?></div></section><?php endforeach;?>
<?php endif;?></div>
<style>
main > .max-w-7xl > section:first-of-type > .flex.items-end{display:none}
main > .max-w-7xl > section:first-of-type{margin-bottom:3rem}
main [data-carousel] [data-slide] > div.relative{min-height:<?=$carouselMobile?>px!important;padding:1rem 3.5rem 1rem 1rem!important;box-sizing:border-box!important}
main [data-carousel] [data-slide] h3{font-size:clamp(1.15rem,4vw,2rem)!important}main [data-carousel] [data-slide] p{display:none}
@media (min-width:768px){main [data-carousel] [data-slide] > div.relative{min-height:<?=$carouselDesktop?>px!important;padding:1.75rem 4rem!important}main [data-carousel] [data-slide] p{display:block}}
</style>
<script>document.querySelector('[data-carousel]')?.setAttribute('data-interval','<?=$carouselSpeed?>')</script>
<?php require ROOT.'/templates/frontend/footer.php';?>
