<?php
try{$db->exec("ALTER TABLE categories ADD COLUMN grid_style VARCHAR(30) NOT NULL DEFAULT 'cards-3' AFTER description");}catch(Throwable){}
$cats=$db->query("SELECT c.*,COUNT(p.id) total FROM categories c LEFT JOIN posts p ON p.category_id=c.id AND p.status='published' AND p.deleted_at IS NULL GROUP BY c.id ORDER BY c.name")->fetchAll();
$catSlug=trim($_GET['kategori']??'');$active=null;foreach($cats as $c)if($c['slug']===$catSlug)$active=$c;
$baseWhere="p.status='published' AND p.deleted_at IS NULL";$metaTitle=($active?$active['name'].' - ':'').'Berita '.Database::setting('school_name','Sekolah');$newsEmpty=Database::setting('news_empty_text','Belum ada berita pada kategori ini.');require ROOT.'/templates/frontend/header.php';
function newsCard(array $p,string $extra=''):string{$cv=Helper::cover($p['featured_image']??'','berita-'.$p['slug'],800,520);return '<article class="group bg-white dark:bg-slate-800 rounded-2xl border overflow-hidden card-hover reveal '.$extra.'"><a href="'.Helper::url('berita/'.$p['slug']).'" class="block overflow-hidden"><img src="'.Helper::e($cv).'" alt="'.Helper::e($p['title']).'" class="w-full h-48 object-cover group-hover:scale-105 transition duration-700" loading="lazy"></a><div class="p-4"><a href="'.Helper::url('berita?kategori='.($p['cat_slug']??'')).'" class="text-[10px] uppercase tracking-wider font-bold text-emerald-600">'.Helper::e($p['cat']??'Berita').'</a><h3 class="news-card-title font-extrabold text-lg leading-snug mt-1.5"><a href="'.Helper::url('berita/'.$p['slug']).'">'.Helper::e($p['title']).'</a></h3><p class="text-xs text-slate-400 mt-2">'.Helper::tgl($p['published_at']??$p['created_at']).' &bull; '.number_format((int)$p['views']).' dibaca</p><p class="news-card-excerpt text-sm text-slate-500 mt-2 line-clamp-2">'.Helper::e(Helper::excerpt($p['excerpt']?:$p['content'],100)).'</p></div></article>';}
function newsGrid(array $rows,string $style):string{ob_start();if($style==='masonry'){echo '<div class="columns-1 sm:columns-2 lg:columns-3 gap-5">';foreach($rows as $p)echo '<div class="break-inside-avoid mb-5">'.newsCard($p).'</div>';echo '</div>';}elseif($style==='timeline'){echo '<div class="max-w-7xl border-l-2 border-emerald-200 pl-7 space-y-5">';foreach($rows as $p)echo '<div class="relative">'.newsCard($p).'</div>';echo '</div>';}else{$cols=in_array($style,['cards-2','horizontal'],true)?'md:grid-cols-2':($style==='cards-4'?'sm:grid-cols-2 lg:grid-cols-4':'md:grid-cols-3');echo '<div class="grid '.$cols.' gap-5">';foreach($rows as $i=>$p)echo newsCard($p,$style==='magazine'&&$i===0?'md:col-span-2':($style==='horizontal'?'sm:grid sm:grid-cols-[180px_1fr]':''));echo '</div>';}return ob_get_clean();}
$fetch=function(string $where,array $args=[],int $limit=6)use($db,$baseWhere){$st=$db->prepare("SELECT p.*,c.name cat,c.slug cat_slug FROM posts p LEFT JOIN categories c ON c.id=p.category_id WHERE $baseWhere".($where?' AND '.$where:'')." ORDER BY p.published_at DESC LIMIT $limit");$st->execute($args);return $st->fetchAll();};
$carouselLimit=max(1,min(10,(int)Database::setting('news_carousel_limit','5')));$carouselSpeed=max(1000,min(20000,(int)Database::setting('news_carousel_speed','5000')));$carouselMobile=max(150,min(420,(int)Database::setting('news_carousel_mobile_height','200')));$carouselDesktop=max(180,min(520,(int)Database::setting('news_carousel_desktop_height','270')));$featured=$fetch('',[],$carouselLimit);
$latestSidebar=$fetch('',[],5);
try{$newsWidgets=$db->query("SELECT * FROM widgets WHERE area='sidebar' AND is_active=1 ORDER BY sort_order,id")->fetchAll();}catch(Throwable){$newsWidgets=[];}
$widgetTypes=array_column($newsWidgets,'type');$widgetAgenda=[];$widgetAnnouncements=[];
if(in_array('agenda',$widgetTypes,true)){try{$widgetAgenda=$db->query("SELECT * FROM agenda WHERE status='published' AND event_date>=CURDATE() ORDER BY event_date LIMIT 5")->fetchAll();}catch(Throwable){}}
if(in_array('announcements',$widgetTypes,true)){try{$widgetAnnouncements=$db->query("SELECT * FROM announcements WHERE status='published' ORDER BY published_at DESC LIMIT 5")->fetchAll();}catch(Throwable){}}
if($active){$posts=$fetch('p.category_id=?',[$active['id']],12);$grid=$active['grid_style']??'cards-3';}
?>
<div class="w-full px-4 md:px-8 py-10">
<?php
$heroBadge='<i class="fa fa-newspaper text-amber-300"></i>Berita Sekolah';
$heroTitle=$active?$active['name']:'Berita';
$heroDesc=$active?(!empty($active['description'])?nl2br(Helper::e($active['description'])):''):'';
$heroCrumb='<a href="'.Helper::url().'" class="hover:text-white">Beranda</a> / Berita'.($active?' / '.Helper::e($active['name']):'');
$heroTheme='sky';
$heroStats=[['icon'=>'fa-newspaper','label'=>count($featured).' sorotan','solid'=>true],['icon'=>'fa-tags','label'=>count($cats).' kategori','solid'=>false]];
$heroActions='<a href="'.Helper::url('indeks-berita').'" class="inline-flex items-center gap-2 bg-white text-slate-900 px-4 py-2 rounded-xl font-bold"><i class="fa fa-layer-group text-sky-600"></i>Indeks Berita</a>';
require ROOT.'/templates/frontend/page-hero.php'; ?>
<div class="mt-4 grid lg:grid-cols-[minmax(0,1fr)_320px] gap-6 items-start"><div class="min-w-0">
<?php if($active): ?>
<?php if(!$posts):?><div class="rounded-3xl border bg-white p-14 text-center text-slate-500"><?=Helper::e($newsEmpty)?></div><?php else:echo newsGrid($posts,$grid);endif;?>
<?php else: ?>
<?php if($featured):?><section class="mb-14"><div class="flex items-end justify-between mb-5"><div><span class="text-xs font-bold uppercase tracking-[.2em] text-emerald-600">Sorotan terbaru</span><h2 class="text-2xl md:text-3xl font-extrabold mt-1">Kabar utama sekolah</h2></div></div><div class="relative overflow-hidden rounded-3xl bg-slate-950 text-white grid" data-carousel><?php foreach($featured as $i=>$p):$cv=Helper::cover($p['featured_image']??'','featured-'.$p['slug'],1200,700);?><article data-slide class="col-start-1 row-start-1 <?= $i?'opacity-0 pointer-events-none':'opacity-100' ?> transition-opacity duration-700"><img src="<?=Helper::e($cv)?>" alt="<?=Helper::e($p['title'])?>" class="absolute inset-0 w-full h-full object-cover"><span class="absolute inset-0 bg-gradient-to-r from-slate-950/90 via-slate-900/45 to-transparent"></span><div class="relative flex items-center w-full p-6 md:p-12 text-left"><div class="max-w-2xl w-full text-left ml-0 mr-auto flex flex-col justify-center items-start my-auto"><span class="text-xs font-bold uppercase tracking-wider text-emerald-300"><?=Helper::e($p['cat']??'Berita')?></span><h3 class="text-2xl md:text-4xl font-extrabold mt-2 leading-tight text-left"><?=Helper::e($p['title'])?></h3><p class="text-sm text-slate-300 mt-3 max-w-xl text-left"><?=Helper::e(Helper::excerpt($p['excerpt']?:$p['content'],150))?></p><a href="<?=Helper::url('berita/'.$p['slug'])?>" class="inline-flex mt-5 bg-emerald-600 text-white px-5 py-2.5 rounded-xl font-bold">Baca berita <i class="fa fa-arrow-right ml-2 mt-1 text-xs"></i></a></div></div></article><?php endforeach;?><button data-prev aria-label="Sebelumnya" class="absolute left-3 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-white/20 grid place-items-center"><i class="fa fa-chevron-left"></i></button><button data-next aria-label="Berikutnya" class="absolute right-3 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-white/20 grid place-items-center"><i class="fa fa-chevron-right"></i></button></div></section><?php endif;?>
<?php foreach($cats as $c):$rows=$fetch('p.category_id=?',[$c['id']],4);if(!$rows)continue;$g=$c['grid_style']??'cards-3';$cols=$g==='cards-2'?'md:grid-cols-2':($g==='cards-4'?'sm:grid-cols-2 lg:grid-cols-4':'md:grid-cols-3');?><section class="mb-14"><div class="flex flex-wrap items-end justify-between gap-3 mb-5"><div><span class="text-xs font-bold uppercase tracking-[.18em] text-emerald-600">Kategori berita</span><h2 class="text-2xl font-extrabold mt-1"><?=Helper::e($c['name'])?></h2><?php if($c['description']):?><p class="text-sm text-slate-500 mt-1"><?=Helper::e($c['description'])?></p><?php endif;?></div><a href="<?=Helper::url('berita?kategori='.$c['slug'])?>" class="text-sm font-bold text-emerald-600">Lihat semua <i class="fa fa-arrow-right ml-1"></i></a></div><div class="grid <?=$cols?> gap-5"><?php foreach($rows as $p)echo newsCard($p);?></div></section><?php endforeach;?>
<?php endif;?></div>
<aside class="grid gap-4 lg:sticky lg:top-24">
<?php if($latestSidebar): ?><section class="rounded-2xl border bg-white dark:bg-slate-800 dark:border-slate-700 p-4 reveal"><div class="flex items-center gap-2 mb-3"><span class="w-9 h-9 rounded-xl bg-emerald-100 dark:bg-emerald-900 text-emerald-700 dark:text-emerald-200 grid place-items-center"><i class="fa fa-clock-rotate-left"></i></span><h2 class="font-extrabold">Berita Terbaru</h2></div><div class="grid gap-3"><?php foreach($latestSidebar as $lp):$lcv=Helper::cover($lp['featured_image']??'','berita-'.$lp['slug'],300,200);?><a href="<?=Helper::url('berita/'.$lp['slug'])?>" class="group flex gap-3 min-w-0"><img src="<?=Helper::e($lcv)?>" alt="<?=Helper::e($lp['title'])?>" class="w-20 h-16 rounded-xl object-cover shrink-0" loading="lazy"><span class="min-w-0"><strong class="block text-sm leading-snug line-clamp-2 group-hover:text-emerald-600"><?=Helper::e($lp['title'])?></strong><small class="block text-slate-400 mt-1"><?=Helper::tgl($lp['published_at']??$lp['created_at'])?></small></span></a><?php endforeach;?></div></section><?php endif;?>
<?php foreach($newsWidgets as $w):$wt=$w['type'];$wc=trim((string)($w['content']??''));$wic=['agenda'=>'fa-calendar-check','announcements'=>'fa-bullhorn','posts'=>'fa-newspaper','image'=>'fa-image','contact'=>'fa-address-book','social'=>'fa-share-nodes','text'=>'fa-align-left','html'=>'fa-code'][$wt]??'fa-puzzle-piece';$anim=$w['animation']??'zoom';$animClass=['none'=>'','zoom'=>'transition duration-700 ease-out hover:scale-105 hover:brightness-105','lift'=>'transition duration-500 ease-out hover:-translate-y-1 hover:scale-[1.02]','grayscale'=>'grayscale transition duration-500 hover:grayscale-0','blur'=>'blur-[1.5px] transition duration-500 hover:blur-0 hover:scale-[1.02]'][$anim]??'';?><section class="rounded-2xl border border-slate-200/80 bg-white dark:bg-slate-800 dark:border-slate-700 p-4 reveal overflow-hidden shadow-sm"><?php if(!empty($w['title'])):?><div class="flex items-center gap-2.5 mb-3"><span class="w-9 h-9 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 text-white grid place-items-center shadow-sm"><i class="fa <?=$wic?>"></i></span><h2 class="font-extrabold leading-tight"><?=Helper::e($w['title'])?></h2></div><?php endif;?>
<?php if($wt==='image'&&$wc!==''):$imageLink='';$imageBlank=false;$imageValue=trim(strip_tags(html_entity_decode($wc,ENT_QUOTES|ENT_HTML5,'UTF-8')));try{$pj=json_decode($wc,true);if(is_array($pj)&&!empty($pj['src'])){$imageValue=trim(strip_tags(html_entity_decode($pj['src'],ENT_QUOTES|ENT_HTML5,'UTF-8')));$imageLink=trim($pj['link']??'');$imageBlank=!empty($pj['blank']);}}catch(Throwable){}$wi=(preg_match('~^(?:https?:)?//~i',$imageValue)||str_starts_with($imageValue,'/'))?$imageValue:Helper::upload($imageValue);?><div class="rounded-xl overflow-hidden bg-slate-100 dark:bg-slate-700"><?php if($imageLink!==''):[$wHref,$wAuto]=Helper::menuUrl($imageLink);$wTgt=($imageBlank||$wAuto==='_blank')?' target="_blank" rel="noopener noreferrer"':'';?><a href="<?=Helper::e($wHref)?>"<?=$wTgt?>><img src="<?=Helper::e($wi)?>" alt="<?=Helper::e($w['title']?:'Widget gambar')?>" class="w-full h-auto object-cover <?=$animClass?>" loading="lazy"></a><?php else: ?><img src="<?=Helper::e($wi)?>" alt="<?=Helper::e($w['title']?:'Widget gambar')?>" class="w-full h-auto object-cover <?=$animClass?>" loading="lazy"><?php endif; ?></div>
<?php elseif($wt==='html'):?><div class="widget-html text-sm leading-relaxed"><?=$wc?></div>
<?php elseif($wt==='text'):?><div class="widget-copy text-sm text-slate-600 dark:text-slate-300 leading-relaxed text-justify"><?=$wc?></div>
<?php elseif($wt==='posts'):?><div class="grid gap-2.5"><?php foreach($latestSidebar as $lp):?><a href="<?=Helper::url('berita/'.$lp['slug'])?>" class="text-sm font-semibold leading-snug hover:text-emerald-600"><i class="fa fa-angle-right text-emerald-500 mr-1"></i><?=Helper::e($lp['title'])?></a><?php endforeach;?></div>
<?php elseif($wt==='agenda'):?><div class="grid gap-2.5"><?php foreach($widgetAgenda as $i=>$wa):?><a href="<?=Helper::url('agenda')?>" class="group flex gap-3 rounded-xl border border-slate-100 dark:border-slate-700 bg-slate-50/80 dark:bg-slate-900/30 p-2.5 hover:border-emerald-300 hover:bg-emerald-50/60 dark:hover:bg-slate-700 transition"><span class="w-8 h-8 shrink-0 rounded-lg bg-white dark:bg-slate-700 border dark:border-slate-600 text-emerald-700 dark:text-emerald-300 grid place-items-center text-xs font-extrabold"><?=$i+1?></span><span class="min-w-0"><b class="block text-sm leading-snug group-hover:text-emerald-700"><?=Helper::e($wa['title'])?></b><span class="flex flex-wrap gap-x-2 gap-y-0.5 text-[11px] text-slate-400 mt-1"><span><i class="fa fa-calendar-day mr-1 text-emerald-500"></i><?=Helper::tgl($wa['event_date'])?></span><?php if(!empty($wa['start_time'])):?><span><i class="fa fa-clock mr-1"></i><?=Helper::e(substr((string)$wa['start_time'],0,5))?></span><?php endif;?><?php if(!empty($wa['location'])):?><span class="basis-full truncate"><i class="fa fa-location-dot mr-1"></i><?=Helper::e($wa['location'])?></span><?php endif;?></span></span></a><?php endforeach;?><?php if(!$widgetAgenda):?><p class="rounded-xl bg-slate-50 dark:bg-slate-700/40 p-3 text-sm text-slate-400 text-center">Belum ada agenda mendatang.</p><?php endif;?></div>
<?php elseif($wt==='announcements'):?><?php if($wc!==''):?><div class="widget-copy text-sm text-slate-500 dark:text-slate-300 mb-3 pb-3 border-b dark:border-slate-700"><?=$wc?></div><?php endif;?><div class="grid gap-2.5"><?php foreach($widgetAnnouncements as $i=>$wan):?><a href="<?=Helper::url('pengumuman')?>" class="group flex gap-3 rounded-xl border border-slate-100 dark:border-slate-700 p-2.5 hover:border-amber-300 hover:bg-amber-50/60 dark:hover:bg-slate-700 transition"><span class="w-8 h-8 shrink-0 rounded-lg bg-amber-100 dark:bg-amber-900 text-amber-700 dark:text-amber-200 grid place-items-center text-xs font-extrabold"><?=$i+1?></span><span class="min-w-0"><b class="block text-sm leading-snug group-hover:text-amber-700 line-clamp-2"><?=Helper::e($wan['title'])?></b><small class="block text-slate-400 mt-1"><i class="fa fa-calendar-day mr-1"></i><?=Helper::tgl($wan['published_at']??$wan['created_at'])?></small></span></a><?php endforeach;?><?php if(!$widgetAnnouncements):?><p class="rounded-xl bg-slate-50 dark:bg-slate-700/40 p-3 text-sm text-slate-400 text-center">Belum ada pengumuman.</p><?php endif;?></div>
<?php elseif($wt==='contact'):?><div class="grid gap-2 text-sm text-slate-600 dark:text-slate-300"><p><i class="fa fa-location-dot text-emerald-600 w-5"></i><?=Helper::e(Database::setting('address','-'))?></p><p><i class="fa fa-phone text-emerald-600 w-5"></i><?=Helper::e(Database::setting('phone','-'))?></p><p><i class="fa fa-envelope text-emerald-600 w-5"></i><?=Helper::e(Database::setting('email','-'))?></p></div>
<?php elseif($wt==='social'):?><div class="flex flex-wrap gap-2"><?php foreach(['facebook'=>'fa-facebook-f','instagram'=>'fa-instagram','youtube'=>'fa-youtube','tiktok'=>'fa-tiktok'] as $sn=>$si):$su=Database::setting($sn,'');if(!$su)continue;?><a href="<?=Helper::e($su)?>" target="_blank" rel="noopener noreferrer" class="w-10 h-10 rounded-xl bg-slate-100 dark:bg-slate-700 grid place-items-center hover:bg-emerald-600 hover:text-white" aria-label="<?=ucfirst($sn)?>"><i class="fab <?=$si?>"></i></a><?php endforeach;?></div>
<?php elseif($wc!==''):?><div class="text-sm text-slate-600 dark:text-slate-300"><?=nl2br(Helper::e($wc))?></div><?php endif;?></section><?php endforeach;?>
</aside></div>
<style>
.news-card-title{text-align:left}
.news-card-excerpt{text-align:justify;text-align-last:left}
.widget-copy p{margin:.35rem 0}.widget-copy ul{list-style:disc;padding-left:1.25rem}.widget-copy ol{list-style:decimal;padding-left:1.25rem}.widget-copy a{color:#059669;font-weight:700}
main > .max-w-7xl > section:first-of-type > .flex.items-end{display:none}
main > .max-w-7xl > section:first-of-type{margin-bottom:3rem}
main [data-carousel] [data-slide] > div.relative{min-height:<?=$carouselMobile?>px!important;padding:1rem 3.5rem 1rem 1rem!important;box-sizing:border-box!important}
main [data-carousel] [data-slide] h3{font-size:clamp(1.15rem,4vw,2rem)!important}main [data-carousel] [data-slide] p{display:none}
@media (min-width:768px){main [data-carousel] [data-slide] > div.relative{min-height:<?=$carouselDesktop?>px!important;padding:1.75rem 4rem!important}main [data-carousel] [data-slide] p{display:block}}
</style>
<script>document.querySelector('[data-carousel]')?.setAttribute('data-interval','<?=$carouselSpeed?>')</script>
<?php require ROOT.'/templates/frontend/footer.php';?>
